image: python:3.13

pipelines:
  pull-requests:
    "**":
      - parallel:
          - step:
              name: lint frontend
              script:
                - pip install flake8
                - python check.py --frontend lint
          - step:
              name: format frontend
              script:
                - pip install black
                - python check.py --frontend fmt-check
          - step:
              name: lint backend
              script:
                - pip install flake8
                - python check.py --backend lint
          - step:
              name: format backend
              script:
                - pip install black
                - python check.py --backend fmt-check

  custom:
    manual-checks-all:
      - step:
          name: Run all checks manually
          image: python:3.13
          script:
            - pip install flake8 black
            - python check.py --frontend lint
            - python check.py --frontend fmt-check
            - python check.py --backend lint
            - python check.py --backend fmt-check

    manual-checks-backend:
      - step:
          name: Run backend checks manually
          image: python:3.13
          script:
            - pip install flake8 black
            - python check.py --backend lint
            - python check.py --backend fmt-check

    manual-checks-frontend:
      - step:
          name: Run frontend checks manually
          image: python:3.13
          script:
            - pip install flake8 black
            - python check.py --frontend lint
            - python check.py --frontend fmt-check
