version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    environment:
      - API_URL=http://backend-api:8000
    depends_on:
      - backend-api
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./database:/database
    env_file:
      - ./backend/.env
    environment:
      - CHROMA_DB_PATH=/database
    restart: unless-stopped

  # Pipeline is defined but not started automatically
  backend-pipeline:
    build:
      context: ./backend
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./database:/database
    env_file:
      - ./backend/.env
    environment:
      - CHROMA_DB_PATH=/database
    # No automatic execution - will only run when explicitly called
    profiles: ["manual"]